![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)

## NumPy Grundlagen: Arrays erstellen, Indexing und mathematische Operationen
In dieser Schulung werden wir die Grundlagen von NumPy behandeln. Ziel ist es, Arrays zu erstellen, die grundlegenden Indexierungsoperationen zu verstehen und mathematische Berechnungen durchzuführen. 

### Installation

Bevor du NumPy nutzen kannst, musst du es installieren. Dafür gibt es zwei einfache Möglichkeiten:

Über die Python-Paketverwaltung `pip`:
   ```bash
   pip install numpy

**Importieren:**
Nach der Installation kannst du NumPy in deinem Python-Skript oder Jupyter Notebook importieren. Die übliche Praxis ist, NumPy mit dem Alias np zu importieren:

In [4]:
import numpy as np

Das macht den Code kürzer und übersichtlicher. Anstatt jedes Mal numpy.array zu schreiben, kannst du einfach np.array verwenden.

**NumPy-Version ausgeben:** 
Um zu überprüfen, ob NumPy korrekt installiert wurde, kannst du die Version abfragen:

In [6]:
print("NumPy Version:", np.__version__)

NumPy Version: 1.26.4


---

### Arrays erstellen
NumPy bietet verschiedene Methoden, Arrays zu erstellen. 

#### 1. Manuelles Erstellen von Arrays
Arrays können manuell durch Listen oder Tupel erstellt werden.

In [2]:
import numpy as np

In [3]:
array_a = np.array([1, 2, 3, 4])
print("Manuell erstelltes Array:", array_a)

Manuell erstelltes Array: [1 2 3 4]


#### 2. Erstellen von Arrays mit NumPy-Funktionen
NumPy bietet Funktionen, um Arrays direkt zu erstellen:

In [14]:
zeros_array = np.zeros((2, 3))  # Array mit Nullen, 2x3 Matrix
ones_array = np.ones((3, 3))  # Array mit Einsen, 3x3 Matrix
range_array = np.arange(0, 10, 2)  # Array von 0 bis 10 mit Inkrementen von 2
linspace_array = np.linspace(0, 1, 5)  # 5 gleichmäßige Punkte zwischen 0 und 1

In [15]:
print("Array mit Nullen:")
print(zeros_array)
print("\nArray mit Einsen:")
print(ones_array)
print("\nArray mit einer Range:", range_array)
print("\nArray mit Linspace:", linspace_array)

Array mit Nullen:
[[0. 0. 0.]
 [0. 0. 0.]]

Array mit Einsen:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array mit einer Range: [0 2 4 6 8]

Array mit Linspace: [0.   0.25 0.5  0.75 1.  ]


#### Typanpassung
Beim Erstellen eines Arrays kann der Datentyp festgelegt werden:

In [4]:
array = np.array([1, 2, 3], dtype=float)
print(array)

[1. 2. 3.]


#### 3. Zufallsarrays
Zufällige Werte können nützlich sein, um Daten zu simulieren.

In [ ]:
random_array = np.random.rand(3, 3)  # Werte zwischen 0 und 1 einer 3x3 Matrix
random_int_array = np.random.randint(
    0, 100, (2, 2)
)  # Ganzzahlen in einer Range von 10 bis 100 in einer 2x2 Matrix

In [8]:
print("\nZufallsarray:")
print(random_array)

print("\nZufallsarray mit Ganzzahlen:")
print(random_int_array)


Zufallsarray:
[[0.59963012 0.47558839 0.31966224]
 [0.63904513 0.44130106 0.80858285]
 [0.02421211 0.63516455 0.74836388]]

Zufallsarray mit Ganzzahlen:
[[75 38]
 [84 54]]


#### 4. 📘 NumPy Arrays – Eigenschaften verstehen


##### 🛠️ Beispiel: Erstellen eines 2D-Arrays

In [20]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", array)

Array:
 [[1 2 3]
 [4 5 6]]


#### 🧾 Eigenschaften eines Arrays
NumPy-Arrays besitzen hilfreiche Eigenschaften, die dich bei der Analyse und Bearbeitung deiner Daten unterstützen:

| Eigenschaft | Bedeutung | Beispiel |
|-------------|-----------|----------|
| `ndim`      | Anzahl der Dimensionen | `2` |
| `shape`     | Zeilen und Spalten | `(2, 3)` |
| `size`      | Gesamtanzahl der Elemente | `6` |
| `dtype`     | Datentyp der Einträge | `int64` |

#### 🔍 Schauen wir uns die verschiedenen Array-Dimensionen und ihre Eigenschaften anhand von Beispielen an:

##### 📏 1️⃣ **1D-Array** – eindimensional

In [31]:
array_1d = np.array([10, 20, 30, 40])
print("1D-Array:\n", array_1d)

print("ndim:", array_1d.ndim)
print("shape:", array_1d.shape)
print("size:", array_1d.size)
print("dtype:", array_1d.dtype)

1D-Array:
 [10 20 30 40]
ndim: 1
shape: (4,)
size: 4
dtype: int32


##### 🧮 2️⃣ **2D-Array** – zweidimensional (Matrix)

In [33]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D-Array:\n", array_2d)

print("ndim:", array_2d.ndim)
print("shape:", array_2d.shape)
print("size:", array_2d.size)
print("dtype:", array_2d.dtype)


2D-Array:
 [[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
size: 6
dtype: int32


##### 🧊 3️⃣ **3D-Array** – dreidimensional (z. B. Stapel von Matrizen)

In [35]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D-Array:\n", array_3d)

print("ndim:", array_3d.ndim)
print("shape:", array_3d.shape)
print("size:", array_3d.size)
print("dtype:", array_3d.dtype)


3D-Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3
shape: (2, 2, 2)
size: 8
dtype: int32


##### 🌌 🔢 **Mehrdimensionales Array (4D)**

In [37]:
array_4d = np.ones((2, 3, 4, 5))
print("\n4D-Array mit Einsen:\n", array_4d)

print("ndim:", array_4d.ndim)
print("shape:", array_4d.shape)
print("size:", array_4d.size)
print("dtype:", array_4d.dtype)


4D-Array mit Einsen:
 [[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]
ndim: 4
shape: (2, 3, 4, 5)
size: 120
dtype: float64




##### ✅ Hinweis:

> Je höher die Dimension (`ndim`), desto komplexer die Struktur des Arrays. In der Praxis reichen oft 1D–3D für typische Anwendungsfälle (Vektoren, Matrizen, Bildverarbeitung etc.).

### Array-Indexing und Slicing
Arrays in NumPy unterstützen leistungsstarkes Indexing und Slicing.

#### 1. Einfache Indizierung

In [41]:
array_b = np.array([10, 20, 30, 40, 50])
print("Element an Index 2:", array_b[2])  # Zugriff auf das dritte Element

Element an Index 2: 30


#### 2. Slicing

In [43]:
print("Slicing von Index 1 bis 3:", array_b[1:4])  # Enthält Index 1, 2, 3

Slicing von Index 1 bis 3: [20 30 40]


#### 3. Multidimensionale Arrays

In [45]:
multi_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMultidimensionales Array:")
print(multi_array)
print("Element in Zeile 2, Spalte 3:", multi_array[1, 2])
print("Alle Elemente aus Spalte 3:", multi_array[:, 2])
print("Alle Elemente bis Zeile 3:", multi_array[:2])
print("Alle Elemente bis Zeile 3 aus Spalte 3:", multi_array[:2, 2])


Multidimensionales Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element in Zeile 2, Spalte 3: 6
Alle Elemente aus Spalte 3: [3 6 9]
Alle Elemente bis Zeile 3: [[1 2 3]
 [4 5 6]]
Alle Elemente bis Zeile 3 aus Spalte 3: [3 6]


#### Änderung der Struktur

- Reshape:

In [13]:
array = np.array([[1, 2], [3, 4]])
print(f"Das Ausgangsarray: {array}")
print()
reshaped = array.reshape((1, 4))  # Neue Form mit 1 Zeile und 4 Spalten
print(reshaped)

Das Ausgangsarray: [[1 2]
 [3 4]]

[[1 2 3 4]]


- Transponieren:

In [14]:
transposed = array.T
print(transposed)

[[1 3]
 [2 4]]


### Mathematische Operationen
NumPy bietet eine Vielzahl von mathematischen Operationen für Arrays.

#### 1. Elementweise Operationen
Die Operationen werden immer elementweise ausgeführt, d.h. es werden immer die einzelnen Elemente des Arrays betrachtet:

In [16]:
array_c = np.array([1, 2, 3, 4])
array_d = np.array([5, 6, 7, 8])

In [49]:
addition = array_c + array_d
multiplication = array_c * array_d
square = array_c**2

In [50]:
print("Addition:", addition)
print("Multiplikation:", multiplication)
print("Quadrat:", square)

Addition: [ 6  8 10 12]
Multiplikation: [ 5 12 21 32]
Quadrat: [ 1  4  9 16]


#### 2. Aggregatfunktionen

In [52]:
print("Summe:", np.sum(array_c))
print("Mittelwert:", np.mean(array_c))
print("Maximalwert:", np.max(array_c))

Summe: 10
Mittelwert: 2.5
Maximalwert: 4


#### 3. Matrixoperationen

In [54]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("matrix A:")
print(matrix_a)

print("\nmatrix B:")
print(matrix_b)

matrix A:
[[1 2]
 [3 4]]

matrix B:
[[5 6]
 [7 8]]


#### Wurzeln und Expontentialfunktionen:

In [19]:
array = np.array([[16, 9], [1, 4]])

sqrt_array = np.sqrt(array)
exp_array = np.exp(array)
print(sqrt_array)
print(exp_array)

[[4. 3.]
 [1. 2.]]
[[8.88611052e+06 8.10308393e+03]
 [2.71828183e+00 5.45981500e+01]]


---

## **Erweiterte Themen in NumPy**

### Logische Operationen

In [21]:
array = np.array([1, 2, 3, 4])
mask = array > 2  # liefert True für einzelne Elemente, die größer als 2 sind und sonst False.
print(mask)
print(array[mask])

[False False  True  True]
[3 4]


##### Beispiel: Filtern von Werten mit Boolean Indexing

In [22]:
array = np.array([1, 222, 32, 45, 5, 66])
filtered = array[array > 25]
print(filtered)

[222  32  45  66]


In [ ]:
array = np.array([1, 222, 32, 45, 5, 66])

# Werte zwischen 20 und 40 (exklusiv)
mask = (array > 20) & (array < 40)
print(array[mask])

# Werte kleiner als 15 oder größer als 45
mask = (array < 15) | (array > 45)
print(array[mask])

# Negation: Alle Werte, die NICHT größer als 25 sind
mask = ~(array > 25)
print(array[mask])

[32]
[  1 222   5  66]
[1 5]


#### `np.any()` und `np.all()`

Mit diesen Funktionen kann geprüft werden, ob eine Bedingung für **mindestens ein Element** (`any()`) oder **alle Elemente** (`all()`) erfüllt ist.

In [24]:
array = np.array([1, 222, 32, 45, 5, 66])

# Gibt es Werte größer als 45?
print(np.any(array > 45))  # True

# Sind alle Werte größer als 5?
print(np.all(array > 5))  # True

# Sind alle Werte kleiner als 50?
print(np.all(array < 50))  # False

True
False
False


`sort` zum Sortieren von Werten

In [25]:
array = np.array([3, 1, 2])
sorted_array = np.sort(array)
print(sorted_array)

[1 2 3]


### Übung

**Aufgabe**
1. Erstelle ein Array mit Zufallswerten und berechne die Summe und das Maximum.
2. Simuliere ein kleines Dataset mit `np.arange` und führe Slicing-Operationen darauf aus.


### Lösungen

#### Lösung zu Aufgabe 1

In [58]:
random_array_solution = np.random.rand(5)  # Array mit Zufallswerten
sum_random_array = np.sum(random_array_solution)
max_random_array = np.max(random_array_solution)

In [59]:
print("\nZufallsarray:", random_array_solution)
print("Summe des Arrays:", sum_random_array)
print("Maximalwert des Arrays:", max_random_array)


Zufallsarray: [0.20302288 0.58659516 0.06866773 0.35576324 0.98399288]
Summe des Arrays: 2.1980418906062305
Maximalwert des Arrays: 0.9839928808197687


#### Lösung zu Aufgabe 2

In [61]:
simulated_dataset = np.arange(10, 50, 5)  # Simuliertes Dataset
sliced_dataset = simulated_dataset[2:5]  # Slicing von Index 2 bis 4

In [62]:
print("\nSimuliertes Dataset:", simulated_dataset)
print("Slicing-Ergebnis:", sliced_dataset)


Simuliertes Dataset: [10 15 20 25 30 35 40 45]
Slicing-Ergebnis: [20 25 30]


---

#### `axis`: Zeilen- bzw. spaltenweise Berechnungen

In NumPy spielt der `axis`-Parameter eine wichtige Rolle, wenn mathematische Operationen wie Summen, Mittelwerte oder Standardabweichungen über bestimmte Dimensionen eines Arrays berechnet werden. 

#### Achsen in NumPy-Arrays

Ein NumPy-Array kann eine oder mehrere Dimensionen haben. Jede Dimension wird als Achse (`axis`) bezeichnet:

- In einem **2D-Array (Matrix)** gibt es zwei Achsen:
  - `axis=0`: Spaltenweise Berechnung (Operationen laufen entlang der Zeilen).
  - `axis=1`: Zeilenweise Berechnung (Operationen laufen entlang der Spalten).

Ein Beispiel für ein 2D-Array:

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### `axis`-Parameter in Funktionen

Mit `axis` kann man bestimmen, ob die Berechnung entlang der Zeilen oder Spalten erfolgen soll.

Hier wird jede Zeile für sich addiert:  
`[1+2+3+4, 5+6+7+8, 9+10+11+12]`



In [ ]:
# Summe über die Spalten (spaltenweise)
sum_cols = np.sum(arr, axis=0)
print("Summen spaltenweise:", sum_cols)

Summen spaltenweise: [15 18 21 24]


Hier wird jede Spalte für sich addiert:  
`[1+5+9, 2+6+10, 3+7+11, 4+8+12]`

Ohne `axis` wird die Summe über alle Elemente berechnet:

#### Weitere Operationen mit `axis`

Der `axis`-Parameter kann auch für andere Funktionen verwendet werden, z. B. Mittelwerte oder Standardabweichungen.

Genauso funktionieren `np.median()`, `np.std()` (Standardabweichung) oder `np.prod()` (Produkt).

#### Warum ist `axis` nützlich?

- Erlaubt die gezielte Berechnung für Zeilen oder Spalten, was in der Datenanalyse oft benötigt wird.
- Spart Schleifen und macht Berechnungen effizienter.
- In Kombination mit `reshape()`, `transpose()` oder `swapaxes()` lassen sich Daten für weitere Analysen vorbereiten.

#### `axis` in höheren Dimensionen

Bei mehrdimensionalen Arrays (`ndarray` mit mehr als 2 Dimensionen) erweitert sich das `axis`-Konzept:

- `axis=0`: entlang der ersten Dimension (z. B. Batch-Ebene in Machine Learning).
- `axis=1`: entlang der zweiten Dimension.
- `axis=2`: entlang der dritten Dimension usw.

Je nach Datenstruktur kann das nützlich sein, um z. B. über mehrere Bildkanäle oder Zeitschritte zu aggregieren.

## Fazit

- `axis=0` bedeutet eine Berechnung über die Spalten (Operationen laufen vertikal).
- `axis=1` bedeutet eine Berechnung über die Zeilen (Operationen laufen horizontal).
- Ohne `axis` wird das gesamte Array berücksichtigt.
- Dieses Konzept ist essenziell für effiziente Berechnungen in NumPy.


---

#### **Arrays vs. Listen in Python – Unterschiede und Vorteile**


##### Arrays vs. Listen in Python – Unterschiede und Vorteile


###### Python-Listen – Basics


In [64]:
# Erstellen einer Liste
liste = [1, 2, 3, 4, 5]
print("Liste:", liste)
print("Typ:", type(liste))

Liste: [1, 2, 3, 4, 5]
Typ: <class 'list'>


In [65]:
#  Verschiedene Datentypen in einer Liste
mixed_list = [1, "zwei", 3.0, True]
print("Gemischte Liste:", mixed_list)

Gemischte Liste: [1, 'zwei', 3.0, True]


###### Einführung in NumPy-Arrays


In [67]:
# Erstellen eines Arrays
array = np.array([1, 2, 3, 4, 5])
print("Array:", array)
print("Typ:", type(array))

Array: [1 2 3 4 5]
Typ: <class 'numpy.ndarray'>


In [68]:
# Nur ein Datentyp erlaubt
mixed_array = np.array([1, "zwei", 3.0])  # alles wird zu Strings!
print("Gemischter Array:", mixed_array)
print("Datentyp im Array:", mixed_array.dtype)

Gemischter Array: ['1' 'zwei' '3.0']
Datentyp im Array: <U32


###### Erstellen einer Liste Vorteile von Arrays (insb. NumPy)

- Schneller bei großen numerischen Datenmengen
- Weniger Speicherverbrauch
- Vektor- und Matrixoperationen direkt möglich
- Kompatibel mit vielen Bibliotheken (z. B. SciPy, scikit-learn)
- Broadcasting: Operationen auf ganze Arrays


###### Operationen im Vergleich

In [71]:
print("🔄 Vergleich von Operationen:")
liste = [1, 2, 3]
array = np.array([1, 2, 3])
print(liste)
print(array)

🔄 Vergleich von Operationen:
[1, 2, 3]
[1 2 3]


In [72]:
# Liste: kein Broadcasting
print("Liste + Liste:", liste + liste)  # Verkettung
# Array: elementweise Addition
print("Array + Array:", array + array)  # Addition

Liste + Liste: [1, 2, 3, 1, 2, 3]
Array + Array: [2 4 6]


In [73]:
# Listen erlauben keine Vektoroperationen:
try:
    print("Liste * 2:", liste * 2)  # Wiederholung
except Exception as e:
    print("Fehler bei Liste:", e)

print("Array * 2:", array * 2)  # Elementweise Multiplikation

Liste * 2: [1, 2, 3, 1, 2, 3]
Array * 2: [2 4 6]


####  Wann verwende ich was?

Listen: Wenn du mit heterogenen (gemischten) Daten arbeitest oder kleine Datenmengen hast,
Arrays (NumPy): Wenn du numerische Berechnungen oder große Datenmengen effizient verarbeiten willst


### Verlgeich von Rechnen mit und ohne NumPy

In [87]:
# Ohne NumPy
numbers_no_numpy = range(1, 1000001)
%timeit sum([x**2 for x in numbers_no_numpy])

151 ms ± 6.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [88]:
# Mit NumPy
numbers_numpy = np.arange(1, 1000001)
%timeit np.sum(numbers_numpy**2)

2.44 ms ± 389 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


---

- **Offizielle Dokumentation:** [NumPy-Dokumentation](https://numpy.org/doc/)
- [NumPy für absolute Anfänger](https://numpy.org/doc/stable/user/absolute_beginners)
- [NumPy: Lernen und Ressourcen](https://numpy.org/learn/)
- Bücher:
  - *Python Data Science Handbook* von Jake VanderPlas.
 
  - *Python for Data Analysis* von Wes McKinney.
