![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)

# Inhaltsverzeichnis 

- **Linear Algebra**
    - **Matrizen multiplizieren**
        - **Beispiel 1**
    - **Lineare Gleichungen lösen**
        - **Beispiel 2**
    - **Matrix invertieren**
        - **Beispiel 3**
    - **Diagonalelemente und Spur**


Die Inhalte hier sind optional und nur für alle, die sich gerne etwas mehr mit Mathematik auseinander setzten wollen.

# Linear Algebra 

In diesem Notebook wollen wir auf Funktionen aus `numpy` eingehen, die uns erlauben mit Arrays (bzw. Matrizen) zu rechnen. Dieses Teilgebiet der Mathematik nennt man [**Lineare Algebra**](https://de.wikipedia.org/wiki/Lineare_Algebra). Die meisten Modelle aus dem Bereich des *Data Science* wenden **Lineare Algebra** an. Wir werden zwar später (hauptsächlich) die schon implementierten Modelle praktisch verwenden und dementsprechend nicht selber implementieren, aber ein (kleiner) Überblick über den Umgang mit Matrizen ist immer nützlich.


## Matrizen multiplizieren

Eine häufige Operation, die wir berechnen müssen ist die Multiplikation zweier Matrizen. Siehe z.B. [hier](https://de.wikipedia.org/wiki/Matrizenmultiplikation).

Über den Befehl [`np.dot(X,Y)`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html) können wir zwei Matrizen (Arrays) `X` und `Y` multiplizieren.

**Parameter**:

`X, Y`: Array, bzw. Matrix

**Resultat**:

Die Matrix $\mathbf{X} \cdot \mathbf{Y}$

### Beispiel 1

Wir berechnen das Ergebnis von 

\begin{align}
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}
\cdot 
\begin{pmatrix}
0 & 1 \\
3 & 4 \\
\end{pmatrix}
\end{align}

In [4]:
import numpy as np

In [5]:
X = np.array([[1, 2], [3, 4]])

Y = np.array([[0, 1], [3, 4]])

print("Matrix X:\n", X)
print("Matrix Y:\n", Y)

Z = np.dot(X, Y)
print("Matrix X*Y:\n", Z)

Matrix X:
 [[1 2]
 [3 4]]
Matrix Y:
 [[0 1]
 [3 4]]
Matrix X*Y:
 [[ 6  9]
 [12 19]]


> <span style="color:red"> **_WICHTIG:_** </span> Beachte, dass die Multiplikation mittels `.dot` etwas anderes ist, als `X*Y`. Bei `X*Y` wird die Multiplikation nur *elementweise* ausgeführt. Das ist etwas anderes als die *mathematische* Multiplikation zweier Matrizen durch `.dot`.

In [7]:
X * Y

array([[ 0,  2],
       [ 9, 16]])

> <span style="color:gray"> **_AUFGABE:_** </span> Was ist das Ergebnis von 
\begin{align}
\begin{pmatrix}
1 & 2 \\
5 & 10 \\
\end{pmatrix}\cdot
\begin{pmatrix}
0 & 10 \\
12 & 12 \\
\end{pmatrix} = \qquad ?
\end{align}

## Lineare Gleichungen lösen

Auch [lineare Gleichungen](https://de.wikipedia.org/wiki/Lineares_Gleichungssystem) können wir problemlos mit **Numpy** lösen.
Nehmen wir an, wir haben folgendes (lineares) Gleichungssystem gegeben:

\begin{align}
1\cdot x_1 + 2\cdot x_2 & = 5 \\
3 \cdot x_1 + 4 \cdot x_2 & = 11
\end{align}

**Welche Werte muss $x_1$ und $x_2$ annehmen, damit beide Gleichungen erfüllt sind?**<br>
<br>
Wir können solche Gleichungen immer auch als eine Multiplikation zwischen einer Matrix und einem Vektor schreiben:

\begin{align}
\begin{pmatrix}
1 & 2 \\ 
3 & 4 \\
\end{pmatrix}
\cdot
\begin{pmatrix}
x_1 \\
x_2
\end{pmatrix}
&= 
\begin{pmatrix}
5 \\
11
\end{pmatrix}
\\
\mathbf{A} \cdot 
\begin{pmatrix}
x_1 \\
x_2
\end{pmatrix}
&= \mathbf{b}
\end{align} 
In dieser Form können wir die Gleichung lösen mit dem Befehl

[`np.linalg.solve(A,b)`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html)

### Beispiel 2

Wir wollen das obige Beispiel lösen. Dafür definieren wir als erstes die Matrix $\mathbf{A}$ und den Vektor $\mathbf{b}$:

In [10]:
A = np.array([[1, 2], [3, 4]])

b = np.array([[5], [11]])

Nun können wir die Werte der Funktion übergeben und erhalten die Lösungen für $x_1$ und $x_2$:

In [12]:
y = np.linalg.solve(A, b)
print(y)

[[1.]
 [2.]]


Das bedeutet:
\begin{align}
x_1=1,\quad x_2=2
\end{align}
<br>Und tatsächlich erfüllen diese Werte die obige Gleichung:<br>

\begin{align}
1\cdot 1 + 2\cdot 2 & = 5 \\
3 \cdot 1 + 4 \cdot 2 & = 11
\end{align}


> <span style="color:gray"> **_AUFGABE:_** </span> Für welche Werte $x_1$ und $x_2$ wird folgendes Gleichungssystem gelöst ?
\begin{align}
0\cdot x_1 + 2\cdot x_2 & = 8 \\
5 \cdot x_1 + 4 \cdot x_2 & = 11
\end{align}

<br>
Überprüfe deine Lösung durch Einsetzen.

## Matrix invertieren

Die Einheitsmatrix $\mathbf{I}$ ist die Matrix mit nur 1en auf der Diagonale. Z.b. die zweidimensionale Einheitsmatrix:

\begin{align}
\begin{pmatrix}
1 & 0 \\
0 & 1 \\
\end{pmatrix}
\end{align}

Oft stellt sich in der Mathematik folgende Frage:

**Wenn ich eine Matrix $\mathbf{A}$ gegeben habe, mit welche Matrix muss man $\mathbf{A}$ multiplizieren, damit das Ergebnis die Einheitsmatrix ist?**

Also:

\begin{align}
\mathbf{A} \cdot \mathbf{B} = \begin{pmatrix}
1 & 0 \\
0 & 1 \\
\end{pmatrix}
\end{align}

**Was ist $\mathbf{B}?$**

$\mathbf{B}$ ist die *inverse* Matrix von $\mathbf{A}$. `numpy` bietet uns die Funktion [`inv`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html) um die inverse Matrix einer Matrix zu berechnen.

Diese Funktion erhält als Argument eine Matrix $\mathbf{A}$ und liefert die Inverse Matrix von $\mathbf{A}$ zurück, so dass gilt: 

\begin{align}
\mathbf{A} \cdot inv(\mathbf{A}) = \begin{pmatrix}
1 & 0 \\
0 & 1 \\
\end{pmatrix}
\end{align}

### Beispiel 3

Wir wollen die inverse Matrix von 
\begin{align}
A= \begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}
\end{align}
berechnen:

In [16]:
# A definieren
A = np.array([[1, 2], [3, 4]])

In [17]:
# Die Funktion inv befindet sich im Modul linalg (LINeare ALGebra)
from numpy.linalg import inv

In [18]:
# B ist die inverse Matrix von A
B = inv(A)
B

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**Es gilt nun**

\begin{align}
\mathbf{A} \cdot inv(\mathbf{A}) =
\mathbf{A} \cdot \mathbf{B} =
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix} 
\cdot 
\begin{pmatrix}
-2 & 1 \\
1.5 & -0.5 \\
\end{pmatrix}
=
\begin{pmatrix}
1 & 0 \\
0 & 1 \\
\end{pmatrix}
\end{align}


In [20]:
A.dot(B)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

Der untere linke Wert bedeutet 
\begin{align}
8.8817842 \cdot 10^{-16}
\end{align}
ist also praktisch $0$. Dies liegt an der endlichen Genauigkeit von Python, dass hier nicht *exakt* $0$ als Ergebnis erscheint!

> <span style="color:gray"> **_AUFGABE:_** </span> Überzeuge dich "per Hand", mit Stift und Blatt Papier, dass man bei obiger Multiplikation von $\mathbf{A}$ und $\mathbf{B}$ wirklich die Einheitsmatrix als Ergebnis erhält.

## Diagonalelemente und Spur

Zwei weitere Befehle die häufig von Nutzen sein können, sind [`diag`](https://numpy.org/doc/stable/reference/generated/numpy.diag.html) und [`trace`](https://numpy.org/doc/stable/reference/generated/numpy.trace.html).

Der erste Befehl liefert uns die Diagonalelemente einer Matrix zurück und der zweite Befehl die Summe selbiger.


In [23]:
from numpy import diag, trace

A = np.array([[1, 2], [3, 4]])

print("Die Matrix A")
print(A)

print("Die Elemente auf der Diagonale:")
print(diag(A))

print("Die Summe der Diagonalelemente:")
print(trace(A))

Die Matrix A
[[1 2]
 [3 4]]
Die Elemente auf der Diagonale:
[1 4]
Die Summe der Diagonalelemente:
5
