![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)

# Mathematische und statistische Methoden für NumPy-Arrays

In diesem Notebook betrachten wir einige wichtige mathematische und statistische Funktionen, die uns **NumPy** zur Verfügung stellt.

## Initialisierung von Arrays

Zunächst importieren wir die **NumPy**-Bibliothek und erstellen drei Arrays:
- eine **eindimensionale Matrix** `d1`,
- eine **zweidimensionale Matrix** `d2`,
- eine **dreidimensionale Matrix** `d3`.

Diese Arrays werden verwendet, um verschiedene mathematische und statistische Funktionen praktisch anzuwenden.


In [4]:
import numpy as np

# Erstellung der Arrays
d1 = np.array([0, 1, 2, 3])

d2 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

d3 = np.arange(24).reshape(3, 2, 4)

# Anzeige der Array-Informationen
print("Informationen über die Arrays:")
print(f"1D-Array mit Shape {d1.shape}:\n{d1}\n")
print(f"2D-Array mit Shape {d2.shape}:\n{d2}\n")
print(f"3D-Array mit Shape {d3.shape}:\n{d3}\n")

Informationen über die Arrays:
1D-Array mit Shape (4,):
[0 1 2 3]

2D-Array mit Shape (2, 4):
[[0 1 2 3]
 [4 5 6 7]]

3D-Array mit Shape (3, 2, 4):
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]



Die `shape`-Eigenschaft (`.shape`) gibt die Dimensionen jedes Arrays zurück.


## Bemerkungen zum Parameter `axis`

Der Parameter **`axis`** bestimmt, entlang welcher Achse eine Funktion auf ein NumPy-Array angewendet wird.

### Standardverhalten (`axis=None`)
- Wenn **kein Wert** für `axis` angegeben wird (`axis=None`), wird die Funktion **auf das gesamte Array** angewendet.
- Das bedeutet, dass alle Elemente des Arrays gemeinsam betrachtet werden.

### Bedeutung von `axis` bei mehrdimensionalen Arrays
Die Achsen eines Arrays folgen der Reihenfolge des `shape`-Attributs.  
Beispiel: Ein **2D-Array** mit `shape (2,4)` bedeutet:
- `axis=0` → Berechnung entlang der **Zeilen** (Aggregation über Spalten).
- `axis=1` → Berechnung entlang der **Spalten** (Aggregation über Zeilen).

### Beispiel für `axis` in verschiedenen Dimensionen

#### 1D-Array (`d1`)
Für eindimensionale Arrays gibt es nur eine Achse, daher liefern `axis=None` und `axis=0` dasselbe Ergebnis:


In [7]:
import numpy as np

d1 = np.array([0, 1, 2, 3])
print(np.sum(d1, axis=None))  # Summe über alle Elemente
print(np.sum(d1, axis=0))  # Identisch, da nur eine Achse existiert

6
6


In [8]:
#### 2D-Array (`d2`)

d2 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

print(np.sum(d2, axis=0))  # Summe entlang der Zeilen (pro Spalte)
print(np.sum(d2, axis=1))  # Summe entlang der Spalten (pro Zeile)

[ 4  6  8 10]
[ 6 22]


#### 3D-Array (`d3`)

In [10]:
d3 = np.arange(24).reshape(3, 2, 4)
print("\n", d3)
print("\n", np.sum(d3, axis=0))  # Aggregation über die erste Achse (Blöcke)
print("\n", np.sum(d3, axis=1))  # Aggregation über die zweite Achse (Zeilen)
print("\n", (np.sum(d3, axis=2)))  # Aggregation über die dritte Achse (Spalten)


 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

 [[24 27 30 33]
 [36 39 42 45]]

 [[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]]

 [[ 6 22]
 [38 54]
 [70 86]]



### Zusammenfassung:
| `axis` Wert | Aggregation erfolgt über |
|------------|-------------------------|
| `None`     | Das gesamte Array        |
| `0`        | Die **Zeilen** (über Spalten hinweg) |
| `1`        | Die **Spalten** (über Zeilen hinweg) |
| `2`        | Die dritte Achse (bei 3D-Arrays) |

Die Wahl des richtigen `axis`-Werts hängt also von der gewünschten Berechnung ab.

---


## Elemente mit `np.sum()` aufsummieren 

Die Funktion [`np.sum()`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html) summiert die Elemente eines NumPy-Arrays entweder über das gesamte Array oder entlang einer bestimmten Achse (`axis`).

### Beispiel: `np.sum()` mit verschiedenen Achsen

Wir wenden `np.sum()` auf unsere zuvor definierten Arrays `d1`, `d2` und `d3` an und analysieren das Verhalten je nach `axis`-Wert.

In [13]:
# Arrays definieren
d1 = np.array([0, 1, 2, 3])

d2 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

d3 = np.arange(24).reshape(3, 2, 4)

# 1D-Array
print(f"1D-Array mit Shape {d1.shape}:\n{d1}")

print("\nSumme von d1 | axis=None:")
print(np.sum(d1))  # 0+1+2+3 = 6

# 2D-Array
print(f"\n2D-Array mit Shape {d2.shape}:\n{d2}")

print("\nSumme von d2 | axis=None:")
print(np.sum(d2))  # 0+1+2+3+4+5+6+7 = 28

print("\nSumme von d2 | axis=0 (über Zeilen hinweg, Spaltenweise Summe):")
print(np.sum(d2, axis=0))  # [0+4, 1+5, 2+6, 3+7] -> [4, 6, 8, 10]

print("\nSumme von d2 | axis=1 (über Spalten hinweg, Zeilenweise Summe):")
print(np.sum(d2, axis=1))  # [0+1+2+3, 4+5+6+7] -> [6, 22]

# 3D-Array
print(f"\n3D-Array mit Shape {d3.shape}:\n{d3}")

print("\nSumme von d3 | axis=None (gesamtes Array):")
print(np.sum(d3))  # 0+1+...+23 = 276

print("\nSumme von d3 | axis=0 (über die erste Achse hinweg):")
print(np.sum(d3, axis=0))

1D-Array mit Shape (4,):
[0 1 2 3]

Summe von d1 | axis=None:
6

2D-Array mit Shape (2, 4):
[[0 1 2 3]
 [4 5 6 7]]

Summe von d2 | axis=None:
28

Summe von d2 | axis=0 (über Zeilen hinweg, Spaltenweise Summe):
[ 4  6  8 10]

Summe von d2 | axis=1 (über Spalten hinweg, Zeilenweise Summe):
[ 6 22]

3D-Array mit Shape (3, 2, 4):
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

Summe von d3 | axis=None (gesamtes Array):
276

Summe von d3 | axis=0 (über die erste Achse hinweg):
[[24 27 30 33]
 [36 39 42 45]]


In [14]:
# Summiert Werte über alle "Blöcke" hinweg:
# [[0+8+16, 1+9+17, 2+10+18, 3+11+19],
#  [4+12+20, 5+13+21, 6+14+22, 7+15+23]]

print("\nSumme von d3 | axis=1 (über die zweite Achse hinweg):")
print(np.sum(d3, axis=1))
# Summiert innerhalb jedes Blocks über die Zeilen hinweg

print("\nSumme von d3 | axis=2 (über die dritte Achse hinweg):")
print(np.sum(d3, axis=2))
# Summiert innerhalb jedes Blocks über die Spalten hinweg


Summe von d3 | axis=1 (über die zweite Achse hinweg):
[[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]]

Summe von d3 | axis=2 (über die dritte Achse hinweg):
[[ 6 22]
 [38 54]
 [70 86]]


## Kumulative Summe (`cumsum`)

Die **kumulative Summe** kann mit der Funktion [`np.cumsum()`](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) berechnet werden. Dabei wird jedes Element durch die Summe aller vorhergehenden Elemente ersetzt.

**Hinweis:** Der letzte Wert der kumulativen Summe entspricht der Gesamtsumme des Arrays.

### Beispiel: `np.cumsum()` mit verschiedenen Achsen

Wir betrachten die kumulative Summe für das **zweidimensionale Array `d2`**.

In [17]:
# 2D-Array definieren
d2 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

print(f"2D-Array mit Shape {d2.shape}:\n{d2}")

print("\nKumulative Summe von d2 | axis=None:")
print(np.cumsum(d2))
# Jedes Element ist die Summe aller vorherigen (1D-Reihenfolge)

print("\nKumulative Summe von d2 | axis=0 (spaltenweise Addition):")
print(np.cumsum(d2, axis=0))
# Jede Spalte wird kumulativ über die Zeilen hinweg summiert

print("\nKumulative Summe von d2 | axis=1 (zeilenweise Addition):")
print(np.cumsum(d2, axis=1))
# Jede Zeile wird kumulativ über die Spalten hinweg summiert

2D-Array mit Shape (2, 4):
[[0 1 2 3]
 [4 5 6 7]]

Kumulative Summe von d2 | axis=None:
[ 0  1  3  6 10 15 21 28]

Kumulative Summe von d2 | axis=0 (spaltenweise Addition):
[[ 0  1  2  3]
 [ 4  6  8 10]]

Kumulative Summe von d2 | axis=1 (zeilenweise Addition):
[[ 0  1  3  6]
 [ 4  9 15 22]]


## Produkt (prod)

Das Produkt der Elemente eines Arrays kann mit der Funktion [`prod`](https://numpy.org/doc/stable/reference/generated/numpy.prod.html) entlang einer angegeben Achse berechnet werden.

In [20]:
print(f"1D array with shape {d1.shape}\n{d1}")

print("\nProdukt von d1 | axis=None:")
print(np.prod(d1))  # 0*1*2*3=0

1D array with shape (4,)
[0 1 2 3]

Produkt von d1 | axis=None:
0


In [21]:
print(f"2D array with shape {d2.shape}\n{d2}")

print("\nProdukt von d2 | axis=None:")
print(np.prod(d2))  # 0*1*2*3*4*5*6*7=0

print("\nProdukt von d2 | axis=0:")
print(np.prod(d2, axis=0))  # 0*4=0, 1*5=5, 2*6=12, 3*7=21

print("\nProdukt von d2 | axis=1:")
print(np.prod(d2, axis=1))  # 0*1*2*3=0, 4*5*6*7=840

2D array with shape (2, 4)
[[0 1 2 3]
 [4 5 6 7]]

Produkt von d2 | axis=None:
0

Produkt von d2 | axis=0:
[ 0  5 12 21]

Produkt von d2 | axis=1:
[  0 840]


In [22]:
print(f"3D array with shape {d3.shape}\n{d3}")

print("\nProdukt von d3 | axis=None:")
print(np.prod(d3))  # 0*1*2*3*4*5*6*7=0

print("\nProdukt von d3 | axis=0:")
print(np.prod(d3, axis=0))  # 0*8*16=0, 1*9*17=153, 2*10*18=360, ...

print("\nProdukt von d3 | axis=1:")
print(np.prod(d3, axis=1))  # 0*4=0, 1*5=5, 2*6=12, 3*7=21, ...

print("\nProdukt von d3 | axis=2:")
print(np.prod(d3, axis=2))  # 0*1*2*3=0, 4*5*6*7=840, ...

3D array with shape (3, 2, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

Produkt von d3 | axis=None:
0

Produkt von d3 | axis=0:
[[   0  153  360  627]
 [ 960 1365 1848 2415]]

Produkt von d3 | axis=1:
[[  0   5  12  21]
 [ 96 117 140 165]
 [320 357 396 437]]

Produkt von d3 | axis=2:
[[     0    840]
 [  7920  32760]
 [ 93024 212520]]


## Kumulatives Produkt (cumprod)

Das kumulative Produkt kann mit der Funktion [`cumprod`](https://numpy.org/doc/stable/reference/generated/numpy.cumprod.html) entlang der angegeben Achse berechnet werden. Beachte dabei, dass der letzte Wert immer das Ergebnis des normalen Produktes ist.

In [24]:
print(f"3D array with shape {d3.shape}\n{d3}")

print("\nKumulatives Produkt von d3 | axis=None:")
print(np.cumprod(d3))

print("\nKumulatives Produkt von d3 | axis=0:")
print(np.cumprod(d3, axis=0))

print("\nKumulatives Produkt von d3 | axis=1:")
print(np.cumprod(d3, axis=1))

print("\nKumulatives Produkt von d3 | axis=2:")
print(np.cumprod(d3, axis=2))

3D array with shape (3, 2, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

Kumulatives Produkt von d3 | axis=None:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Kumulatives Produkt von d3 | axis=0:
[[[   0    1    2    3]
  [   4    5    6    7]]

 [[   0    9   20   33]
  [  48   65   84  105]]

 [[   0  153  360  627]
  [ 960 1365 1848 2415]]]

Kumulatives Produkt von d3 | axis=1:
[[[  0   1   2   3]
  [  0   5  12  21]]

 [[  8   9  10  11]
  [ 96 117 140 165]]

 [[ 16  17  18  19]
  [320 357 396 437]]]

Kumulatives Produkt von d3 | axis=2:
[[[     0      0      0      0]
  [     4     20    120    840]]

 [[     8     72    720   7920]
  [    12    156   2184  32760]]

 [[    16    272   4896  93024]
  [    20    420   9240 212520]]]


## Mittelwert

Mit der Funktion [`mean`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html) können wir durch Angabe der Daten und der Achse den Mittelwert eines Arrays berechnen. Dieser Wert wird in der Statistik häufig benötigt.

In [26]:
print(f"2D array with shape {d2.shape}\n{d2}")

print("\nMittelwert von d2 | axis=None:")
print(np.mean(d2))

print("\nMittelwert von d2 | axis=0:")
print(np.mean(d2, axis=0))

print("\nMittelwert von d2 | axis=1:")
print(np.mean(d2, axis=1))

2D array with shape (2, 4)
[[0 1 2 3]
 [4 5 6 7]]

Mittelwert von d2 | axis=None:
3.5

Mittelwert von d2 | axis=0:
[2. 3. 4. 5.]

Mittelwert von d2 | axis=1:
[1.5 5.5]


## Standardabweichung (std)

Mit der Funktion [`std`](https://numpy.org/doc/stable/reference/generated/numpy.std.html) können wir durch Angabe der Daten und der Axis die Standardabweichung berechnen. Die Standardabweichung ist ein Maß dafür, wie sehr gestreut die Daten um den Mittelwert der Daten sind.

In [28]:
print(f"2D array with shape {d2.shape}\n{d2}")

print("\nStandardabweichung von d2 | axis=None:")
print(np.std(d2))

print("\nStandardabweichung von d2 | axis=0:")
print(np.std(d2, axis=0))

print("\nStandardabweichung von d2 | axis=1:")
print(np.std(d2, axis=1))

2D array with shape (2, 4)
[[0 1 2 3]
 [4 5 6 7]]

Standardabweichung von d2 | axis=None:
2.29128784747792

Standardabweichung von d2 | axis=0:
[2. 2. 2. 2.]

Standardabweichung von d2 | axis=1:
[1.11803399 1.11803399]


> <span style="color:gray"> **_AUFGABE:_** </span> Erstelle eine 1-dimensionales Array mit einer beliebigen Größe, aber immer dem gleichen Element. Was ist die Standardabweichung (Streuung) der Daten?

## Varianz (var)

Mit der Funktion [`var`](https://numpy.org/doc/stable/reference/generated/numpy.var.html) können wir durch Angabe der Daten und der Achsen die Varianz berechnen. Die Varianz ist ähnlich der Standardabweichung ein Maß für die Streuung. Es gilt, dass das Quadrat der Standardabweichung die Varianz ist.



In [31]:
print(f"2D array with shape {d2.shape}\n{d2}")

print("\nVarianz von d2 | axis=None:")
print(np.var(d2))

print("\nVarianz von d2 | axis=0:")
print(np.var(d2, axis=0))

print("\nVarianz von d2 | axis=1:")
print(np.var(d2, axis=1))

2D array with shape (2, 4)
[[0 1 2 3]
 [4 5 6 7]]

Varianz von d2 | axis=None:
5.25

Varianz von d2 | axis=0:
[4. 4. 4. 4.]

Varianz von d2 | axis=1:
[1.25 1.25]


## Minimaler und maximaler Wert

[min](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.min.html) und [max](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html) liefern uns den Minimal- bzw. Maximalwert entlang einer Achse.

In [33]:
print(f"2D array with shape {d2.shape}\n{d2}")

print("Minimaler und maximaler Wert von d3 | axis=None:")
print(np.min(d2))
print(np.max(d2))

print("Minimaler und maximaler Wert von d2 | axis=0:")
print(np.min(d2, axis=0))
print(np.max(d2, axis=0))

print("Minimaler und maximaler Wert von d2 | axis=1:")
print(np.min(d2, axis=1))
print(np.max(d2, axis=1))

2D array with shape (2, 4)
[[0 1 2 3]
 [4 5 6 7]]
Minimaler und maximaler Wert von d3 | axis=None:
0
7
Minimaler und maximaler Wert von d2 | axis=0:
[0 1 2 3]
[4 5 6 7]
Minimaler und maximaler Wert von d2 | axis=1:
[0 4]
[3 7]


## Index des minimalen und maximalen Wert

[`argmin`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html?highlight=argmax#numpy.argmax) und [`argmax`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html?highlight=argmax#numpy.argmax) sind ähnlich wie `min` und `max`, nur das in diesem Fall statt des Elements der Index des Elements zurückgegeben wird.

In [35]:
print(f"2D array with shape {d2.shape}\n{d2}")

print("\nIndex des minimalen Elements von d2 | axis=None:")
print(np.argmin(d2))

print("\nIndex des minimalen Elements von d2 | axis=0:")
print(np.argmin(d2, axis=0))


print("\nIndex des minimalen Elements von d2 | axis=1:")
print(np.argmin(d2, axis=1))

2D array with shape (2, 4)
[[0 1 2 3]
 [4 5 6 7]]

Index des minimalen Elements von d2 | axis=None:
0

Index des minimalen Elements von d2 | axis=0:
[0 0 0 0]

Index des minimalen Elements von d2 | axis=1:
[0 0]
