![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)
<div style="float: right; font-size: small;">
    Erstellt von Fakher Ahmed für Data Science. Institut by Fabian Rappert
</div>

# Numpy-Einstiegsaufgaben 
Willkommen zu den NumPy-Einstiegsübungen! 🎉
Hier ist eine Sammlung von Aufgaben, mit denen du deine Numpy-Skills verbessern kannst. Ich habe die Erklärungen und Tipps locker und verständlich gehalten, damit das Ganze Spaß macht. Also, los geht’s!

Es ist völlig in Ordnung, nicht jede Aufgabe sofort lösen zu können! Das Ziel ist es, die Prinzipien und Denkweisen hinter den Lösungen zu verstehen. Wenn du nicht weiterkommst, kannst du Musterlösungen anschauen, kurz nach "NumPy + dein Problem" suchen,  eine AI fragen oder einfach in den Lösungen schauen. 💡

### 1. Importiere das Numpy-Paket
**Aufgabe:** Importiere Numpy unter dem Namen `np`.

**Tipp:** Das machen fast alle so. Es spart Tipparbeit und ist Standard.

In [ ]:
import numpy as np

---

### 2. Erstelle einen Null-Vektor der Größe 10
**Aufgabe:** Erstelle ein Array mit 10 Nullen.

**Tipp:** Verwende die Funktion `np.zeros`.

In [3]:
null_array = np.zeros(10)
null_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---

### 3. Null-Vektor mit einer 1 an Position 5
**Aufgabe:** Erstelle einen Null-Vektor mit 10 Elementen, wobei das 5. Element eine 1 ist.

**Tipp:** Nutze Indexierung, um einzelne Elemente zu ändern.

In [4]:
null_array[4] = 1
null_array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

---

### 4. Vektor mit Werten von 10 bis 49 erstellen
**Aufgabe:** Erstelle einen Vektor mit Zahlen von 10 bis 49 (einschließlich).

**Tipp:** `np.arange` ist dein Freund.

In [5]:
my_array = np.arange(10, 50)
my_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

---

### 5. Vektor umkehren
**Aufgabe:** Drehe die Reihenfolge eines Vektors um.

**Tipp:** Mit Python-Slicing geht das super einfach: `[::-1]`.

In [6]:
my_array[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

---

### 6. 3x3-Matrix mit Werten von 0 bis 8 erstellen
**Aufgabe:** Erstelle eine Matrix (3x3) mit Werten von 0 bis 8.

**Tipp:** Nutze `np.arange` und `reshape`.

In [7]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

---

### 7. 3x3x3-Array mit zufälligen Werten erstellen
**Aufgabe:** Erstelle ein 3x3x3-Array mit zufälligen Zahlen.

**Tipp:** `np.random.random` erstellt Zufallszahlen zwischen 0 und 1.

In [9]:
np.random.random((3, 3, 3))

array([[[0.36086669, 0.52766158, 0.18576824],
        [0.99989726, 0.79653425, 0.99195096],
        [0.08383785, 0.54471609, 0.79084335]],

       [[0.71777634, 0.28845805, 0.7854612 ],
        [0.03807885, 0.77662671, 0.7700437 ],
        [0.79351107, 0.77168424, 0.96832614]],

       [[0.8259323 , 0.78865471, 0.58284295],
        [0.33949497, 0.85782678, 0.18504793],
        [0.21703181, 0.36755633, 0.84765665]]])

---
### 8. Mittelwert eines Zufallsvektors berechnen
**Aufgabe:** Erstelle einen Zufallsvektor der Größe 30 und berechne dessen Mittelwert.

**Tipp:** `np.mean` hilft dir hier weiter.

In [17]:
np.mean(np.random.random(30))

0.514553337772181