![image info](https://user-images.githubusercontent.com/91945811/146929832-e78ff1f4-2739-41b1-acd3-019a39b6a42c.png)
<div style="float: right; font-size: small;">
    Erstellt von Fakher Ahmed für Data Science. Institut by Fabian Rappert
</div>

# Numpy-Einstiegsaufgaben 

### 1. Importiere das Numpy-Paket
**Aufgabe:** Importiere Numpy unter dem Namen `np`.

**Tipp:** Das machen fast alle so. Es spart Tipparbeit und ist Standard.

In [1]:
import numpy as np

---

### 2. Erstelle einen Null-Vektor der Größe 10
**Aufgabe:** Erstelle ein Array mit 10 Nullen.

**Tipp:** Verwende die Funktion `np.zeros`.

In [2]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


---

### 3. Null-Vektor mit einer 1 an Position 5
**Aufgabe:** Erstelle einen Null-Vektor mit 10 Elementen, wobei das 5. Element eine 1 ist.

**Tipp:** Nutze Indexierung, um einzelne Elemente zu ändern.

In [3]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


---

### 4. Vektor mit Werten von 10 bis 49 erstellen
**Aufgabe:** Erstelle einen Vektor mit Zahlen von 10 bis 49 (einschließlich).

**Tipp:** `np.arange` ist dein Freund.

In [4]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


---

### 5. Vektor umkehren
**Aufgabe:** Drehe die Reihenfolge eines Vektors, bspw. aus Aufgabe 7, um.

**Tipp:** Mit Python-Slicing geht das super einfach: `[::-1]`.

In [5]:
z = np.arange(10, 50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


---

### 6. 3x3-Matrix mit Werten von 0 bis 8 erstellen
**Aufgabe:** Erstelle eine Matrix (3x3) mit Werten von 0 bis 8.

**Tipp:** Nutze `np.arange` und `reshape`.

In [6]:
print(np.arange(9))
z = np.arange(9).reshape(3, 3)
print(z)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


---

### 7. 3x3x3-Array mit zufälligen Werten erstellen
**Aufgabe:** Erstelle ein 3x3x3-Array mit zufälligen Zahlen.

**Tipp:** `np.random.random` erstellt Zufallszahlen zwischen 0 und 1.

In [7]:
z = np.random.random((3, 3, 3))
print(z)

[[[0.41957908 0.46008287 0.36419725]
  [0.14781739 0.00519401 0.57658487]
  [0.07039219 0.1938307  0.76668873]]

 [[0.12940608 0.85446107 0.09650373]
  [0.8297144  0.04672989 0.40592262]
  [0.04492236 0.43847711 0.53931201]]

 [[0.71592944 0.30095251 0.24755012]
  [0.57341642 0.99231849 0.24620331]
  [0.08317456 0.32550598 0.88005854]]]


---

### 8. Mittelwert eines Zufallsvektors berechnen
**Aufgabe:** Erstelle einen Zufallsvektor der Größe 30 und berechne dessen Mittelwert.

**Tipp:** `np.mean` hilft dir hier weiter.

In [8]:
z = np.random.random(30)
print(f"Mittelwert: {np.mean(z)}")

Mittelwert: 0.5076746598606489
